version: "3.9"

services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:14.9.0
    environment:
      POSTGRES_DB: MusicService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgrespw"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d WatchBox -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - musicnetwork
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - musicnetwork
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis-data:/data
  app:
    build: ../
    ports:
      - "8080:8080"
    networks:
      - musicnetwork
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  redis-data:
    driver: local
networks:
  musicnetwork:
    driver: bridge